name: sql_crdt
description: Base package for Conflict-free Replicated Data Types (CRDTs) using SQL databases
version: 2.1.5+1
homepage: https://github.com/cachapa/sql_crdt
repository: https://github.com/cachapa/sql_crdt
issue_tracker: https://github.com/cachapa/sql_crdt/issues

environment:
  sdk: ^3.0.0

dependencies:
  crdt: ^5.1.2
#    path: ../crdt
  source_span: ^1.10.0
  sqlparser: ^0.32.1

dev_dependencies:
  lints: any
  test: any
